///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExcelTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ExcelTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("aa1aff8c-bbcb-4f61-a45e-65df48772730")]
    public partial class ExcelTest1Repository : RepoGenBaseFolder
    {
        static ExcelTest1Repository instance = new ExcelTest1Repository();
        ExcelTest1RepositoryFolders.Book16ExcelAppFolder _book16excel;
        ExcelTest1RepositoryFolders.ProgramsAppFolder _programs;
        RepoItemInfo _newsheetInfo;

        /// <summary>
        /// Gets the singleton class instance representing the ExcelTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("aa1aff8c-bbcb-4f61-a45e-65df48772730")]
        public static ExcelTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ExcelTest1Repository() 
            : base("ExcelTest1Repository", "/", null, 0, false, "aa1aff8c-bbcb-4f61-a45e-65df48772730", ".\\RepositoryImages\\ExcelTest1Repositoryaa1aff8c.rximgres")
        {
            _book16excel = new ExcelTest1RepositoryFolders.Book16ExcelAppFolder(this);
            _programs = new ExcelTest1RepositoryFolders.ProgramsAppFolder(this);
            _newsheetInfo = new RepoItemInfo(this, "NewSheet", "/form[@processname='EXCEL']/element[@class='XLDESK']/?/?/?/?/?/button[@name='Add Sheet']", 30000, null, "2277cba0-122c-4b37-ab4f-2dc1b99b6af0");
        }

#region Variables

        string _FontName = "Broadway";

        /// <summary>
        /// Gets or sets the value of variable FontName.
        /// </summary>
        [TestVariable("ad4a39b3-e034-4778-b1e0-e97739c16e97")]
        public string FontName
        {
            get { return _FontName; }
            set { _FontName = value; }
        }

        string _FontValue = "Broadway";

        /// <summary>
        /// Gets or sets the value of variable FontValue.
        /// </summary>
        [TestVariable("996df968-4f59-444f-9668-d7c0be54d0c1")]
        public string FontValue
        {
            get { return _FontValue; }
            set { _FontValue = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("aa1aff8c-bbcb-4f61-a45e-65df48772730")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NewSheet item.
        /// </summary>
        [RepositoryItem("2277cba0-122c-4b37-ab4f-2dc1b99b6af0")]
        public virtual Ranorex.Button NewSheet
        {
            get
            {
                 return _newsheetInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The NewSheet item info.
        /// </summary>
        [RepositoryItemInfo("2277cba0-122c-4b37-ab4f-2dc1b99b6af0")]
        public virtual RepoItemInfo NewSheetInfo
        {
            get
            {
                return _newsheetInfo;
            }
        }

        /// <summary>
        /// The Book16Excel folder.
        /// </summary>
        [RepositoryFolder("ff125acd-eb0f-433d-9030-3d41cdec3670")]
        public virtual ExcelTest1RepositoryFolders.Book16ExcelAppFolder Book16Excel
        {
            get { return _book16excel; }
        }

        /// <summary>
        /// The Programs folder.
        /// </summary>
        [RepositoryFolder("6fc172e3-5f96-4653-8c6b-c8b9cceccd0e")]
        public virtual ExcelTest1RepositoryFolders.ProgramsAppFolder Programs
        {
            get { return _programs; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ExcelTest1RepositoryFolders
    {
        /// <summary>
        /// The Book16ExcelAppFolder folder.
        /// </summary>
        [RepositoryFolder("ff125acd-eb0f-433d-9030-3d41cdec3670")]
        public partial class Book16ExcelAppFolder : RepoGenBaseFolder
        {
            ExcelTest1RepositoryFolders.Sheet1Folder _sheet1;
            ExcelTest1RepositoryFolders.CloseWindowFolder _closewindow;
            ExcelTest1RepositoryFolders.FontTestsFolder _fonttests;
            RepoItemInfo _aiostartdocumentInfo;
            RepoItemInfo _celld5Info;
            RepoItemInfo _cellh8Info;
            RepoItemInfo _cella1Info;
            RepoItemInfo _cellb3Info;
            RepoItemInfo _titlebarbook26excelInfo;
            RepoItemInfo _celle7Info;
            RepoItemInfo _celli12Info;
            RepoItemInfo _mergecenterInfo;
            RepoItemInfo _positionInfo;
            RepoItemInfo _celln1Info;
            RepoItemInfo _editingInfo;
            RepoItemInfo _celln3Info;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _sheettabInfo;
            RepoItemInfo _blankworkbookInfo;

            /// <summary>
            /// Creates a new Book16Excel  folder.
            /// </summary>
            public Book16ExcelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Book16Excel", "/form[@processname='EXCEL']", parentFolder, 30000, null, true, "ff125acd-eb0f-433d-9030-3d41cdec3670", "")
            {
                _sheet1 = new ExcelTest1RepositoryFolders.Sheet1Folder(this);
                _closewindow = new ExcelTest1RepositoryFolders.CloseWindowFolder(this);
                _fonttests = new ExcelTest1RepositoryFolders.FontTestsFolder(this);
                _aiostartdocumentInfo = new RepoItemInfo(this, "AIOStartDocument", ".//container[@automationid='BackstageView']/container[@name='New']/?/?/container[@name='Featured']/button[@name='Blank workbook']", ".//button[@name='Blank workbook']", 30000, null, "a71aa9b2-4f6d-4042-ac21-59b5dfb7f01a");
                _celld5Info = new RepoItemInfo(this, "CellD5", ".//table[@name='Sheet1']/row[@index='5']/cell[@address='D5']", ".//cell[@address='D5']", 30000, null, "6e1c2c8c-411e-42f4-be96-d5b6e27f342f");
                _cellh8Info = new RepoItemInfo(this, "CellH8", ".//table[@name='Sheet1']/row[@index='8']/cell[@address='H8']", ".//cell[@address='H8']", 30000, null, "55301b22-fdd9-4a77-8b31-3347cb64677b");
                _cella1Info = new RepoItemInfo(this, "CellA1", ".//table[@name='Sheet1']/row[@index='1']/cell[@address='A1']", "", 30000, null, "756c7228-cf4d-4a42-a8e3-9120b71fa826");
                _cellb3Info = new RepoItemInfo(this, "CellB3", ".//table[@name='Sheet1']/row[@index='3']/cell[@address='B3']", "", 30000, null, "62692eb4-3fb8-4a64-920f-148f37ba86b0");
                _titlebarbook26excelInfo = new RepoItemInfo(this, "TitleBarBook26Excel", "element[@class='EXCEL2']/container[@caption='Ribbon']//container[@name='Ribbon']/titlebar", ".//titlebar[@name='‪Book8‬  -  Excel']", 30000, null, "81867ab3-2980-422a-ba90-f844544872b2");
                _celle7Info = new RepoItemInfo(this, "CellE7", ".//table[@name='Sheet1']/row[@index='7']/cell[@address='E7']", ".//cell[@address='E7']", 30000, null, "46eee644-8621-4ba7-bb64-ed0368f004ca");
                _celli12Info = new RepoItemInfo(this, "CellI12", ".//table[@name='Sheet1']/row[@index='12']/cell[@address='I12']", ".//cell[@address='I12']", 30000, null, "5becbd7c-0eb6-42f2-97c0-56bc1509938e");
                _mergecenterInfo = new RepoItemInfo(this, "MergeCenter", ".//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Home']/container[@name='Alignment']/button[@name='Merge & Center']/button[@name='Merge & Center']", ".//button[@name='Merge & Center' and @classname='NetUIRibbonButton']", 30000, null, "85250b0f-7063-4c4c-a3ab-8a5106c94da3");
                _positionInfo = new RepoItemInfo(this, "Position", "?/?/workbook[@name='Book29']//scrollbar[@helptext>'Used to change the horizontal']/indicator[@name='Position']", ".//indicator[@classname='NetUIThumb' and @helptext>'Indicates the current horizontal']", 30000, null, "c11a8df2-78f7-4d0a-bb2c-b04ac90b96a0");
                _celln1Info = new RepoItemInfo(this, "CellN1", ".//tabpagelist[@automationid='Book44']/tabpage[@automationid='Sheet1']/?/?/cell[@name='N1']", ".//cell[@name='N1']", 30000, null, "a07fbe10-49f4-408d-9eb6-8f615a213338");
                _editingInfo = new RepoItemInfo(this, "Editing", "element[2]//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Home']/container[@name='Editing']", ".//container[@name='Editing']", 30000, null, "f20e74a8-79dc-4da8-9355-d90c496ad634");
                _celln3Info = new RepoItemInfo(this, "CellN3", ".//tabpagelist[@automationid='Book46']/tabpage[@automationid='Sheet1']/?/?/cell[@name='N3']", ".//cell[@name='N3']", 30000, null, "5c1963a0-66c5-4f3c-b3bc-44e59230145d");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@class='EXCEL2']/container[@caption='Ribbon']//container[@name='Ribbon']/titlebar", ".//titlebar[@name='‪Book2‬  -  Excel']", 30000, null, "b07666dd-bc40-4860-a007-3b85a4846b0a");
                _sheettabInfo = new RepoItemInfo(this, "SheetTab", "element[@class='XLDESK']/?/?/tabpagelist[@automationid='Book61']/button[@name='Sheet Tab Add Sheet']", ".//button[@name='Sheet Tab Add Sheet']", 30000, null, "c276ab32-ba10-4401-815b-73a9ca1713ce");
                _blankworkbookInfo = new RepoItemInfo(this, "BlankWorkbook", ".//container[@automationid='BackstageView']//container[@name='New']/list[@classname='NetUIListView']/listitem[@name='Blank workbook']", ".//listitem[@name='Blank workbook']", 30000, null, "c37f6422-0e45-4d67-bcf2-d3627ea3cd76");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ff125acd-eb0f-433d-9030-3d41cdec3670")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ff125acd-eb0f-433d-9030-3d41cdec3670")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AIOStartDocument item.
            /// </summary>
            [RepositoryItem("a71aa9b2-4f6d-4042-ac21-59b5dfb7f01a")]
            public virtual Ranorex.Button AIOStartDocument
            {
                get
                {
                    return _aiostartdocumentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AIOStartDocument item info.
            /// </summary>
            [RepositoryItemInfo("a71aa9b2-4f6d-4042-ac21-59b5dfb7f01a")]
            public virtual RepoItemInfo AIOStartDocumentInfo
            {
                get
                {
                    return _aiostartdocumentInfo;
                }
            }

            /// <summary>
            /// The CellD5 item.
            /// </summary>
            [RepositoryItem("6e1c2c8c-411e-42f4-be96-d5b6e27f342f")]
            public virtual Ranorex.Cell CellD5
            {
                get
                {
                    return _celld5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellD5 item info.
            /// </summary>
            [RepositoryItemInfo("6e1c2c8c-411e-42f4-be96-d5b6e27f342f")]
            public virtual RepoItemInfo CellD5Info
            {
                get
                {
                    return _celld5Info;
                }
            }

            /// <summary>
            /// The CellH8 item.
            /// </summary>
            [RepositoryItem("55301b22-fdd9-4a77-8b31-3347cb64677b")]
            public virtual Ranorex.Cell CellH8
            {
                get
                {
                    return _cellh8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellH8 item info.
            /// </summary>
            [RepositoryItemInfo("55301b22-fdd9-4a77-8b31-3347cb64677b")]
            public virtual RepoItemInfo CellH8Info
            {
                get
                {
                    return _cellh8Info;
                }
            }

            /// <summary>
            /// The CellA1 item.
            /// </summary>
            [RepositoryItem("756c7228-cf4d-4a42-a8e3-9120b71fa826")]
            public virtual Ranorex.Cell CellA1
            {
                get
                {
                    return _cella1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellA1 item info.
            /// </summary>
            [RepositoryItemInfo("756c7228-cf4d-4a42-a8e3-9120b71fa826")]
            public virtual RepoItemInfo CellA1Info
            {
                get
                {
                    return _cella1Info;
                }
            }

            /// <summary>
            /// The CellB3 item.
            /// </summary>
            [RepositoryItem("62692eb4-3fb8-4a64-920f-148f37ba86b0")]
            public virtual Ranorex.Cell CellB3
            {
                get
                {
                    return _cellb3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellB3 item info.
            /// </summary>
            [RepositoryItemInfo("62692eb4-3fb8-4a64-920f-148f37ba86b0")]
            public virtual RepoItemInfo CellB3Info
            {
                get
                {
                    return _cellb3Info;
                }
            }

            /// <summary>
            /// The TitleBarBook26Excel item.
            /// </summary>
            [RepositoryItem("81867ab3-2980-422a-ba90-f844544872b2")]
            public virtual Ranorex.TitleBar TitleBarBook26Excel
            {
                get
                {
                    return _titlebarbook26excelInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBarBook26Excel item info.
            /// </summary>
            [RepositoryItemInfo("81867ab3-2980-422a-ba90-f844544872b2")]
            public virtual RepoItemInfo TitleBarBook26ExcelInfo
            {
                get
                {
                    return _titlebarbook26excelInfo;
                }
            }

            /// <summary>
            /// The CellE7 item.
            /// </summary>
            [RepositoryItem("46eee644-8621-4ba7-bb64-ed0368f004ca")]
            public virtual Ranorex.Cell CellE7
            {
                get
                {
                    return _celle7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellE7 item info.
            /// </summary>
            [RepositoryItemInfo("46eee644-8621-4ba7-bb64-ed0368f004ca")]
            public virtual RepoItemInfo CellE7Info
            {
                get
                {
                    return _celle7Info;
                }
            }

            /// <summary>
            /// The CellI12 item.
            /// </summary>
            [RepositoryItem("5becbd7c-0eb6-42f2-97c0-56bc1509938e")]
            public virtual Ranorex.Cell CellI12
            {
                get
                {
                    return _celli12Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellI12 item info.
            /// </summary>
            [RepositoryItemInfo("5becbd7c-0eb6-42f2-97c0-56bc1509938e")]
            public virtual RepoItemInfo CellI12Info
            {
                get
                {
                    return _celli12Info;
                }
            }

            /// <summary>
            /// The MergeCenter item.
            /// </summary>
            [RepositoryItem("85250b0f-7063-4c4c-a3ab-8a5106c94da3")]
            public virtual Ranorex.Button MergeCenter
            {
                get
                {
                    return _mergecenterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MergeCenter item info.
            /// </summary>
            [RepositoryItemInfo("85250b0f-7063-4c4c-a3ab-8a5106c94da3")]
            public virtual RepoItemInfo MergeCenterInfo
            {
                get
                {
                    return _mergecenterInfo;
                }
            }

            /// <summary>
            /// The Position item.
            /// </summary>
            [RepositoryItem("c11a8df2-78f7-4d0a-bb2c-b04ac90b96a0")]
            public virtual Ranorex.Indicator Position
            {
                get
                {
                    return _positionInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Position item info.
            /// </summary>
            [RepositoryItemInfo("c11a8df2-78f7-4d0a-bb2c-b04ac90b96a0")]
            public virtual RepoItemInfo PositionInfo
            {
                get
                {
                    return _positionInfo;
                }
            }

            /// <summary>
            /// The CellN1 item.
            /// </summary>
            [RepositoryItem("a07fbe10-49f4-408d-9eb6-8f615a213338")]
            public virtual Ranorex.Cell CellN1
            {
                get
                {
                    return _celln1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellN1 item info.
            /// </summary>
            [RepositoryItemInfo("a07fbe10-49f4-408d-9eb6-8f615a213338")]
            public virtual RepoItemInfo CellN1Info
            {
                get
                {
                    return _celln1Info;
                }
            }

            /// <summary>
            /// The Editing item.
            /// </summary>
            [RepositoryItem("f20e74a8-79dc-4da8-9355-d90c496ad634")]
            public virtual Ranorex.Container Editing
            {
                get
                {
                    return _editingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Editing item info.
            /// </summary>
            [RepositoryItemInfo("f20e74a8-79dc-4da8-9355-d90c496ad634")]
            public virtual RepoItemInfo EditingInfo
            {
                get
                {
                    return _editingInfo;
                }
            }

            /// <summary>
            /// The CellN3 item.
            /// </summary>
            [RepositoryItem("5c1963a0-66c5-4f3c-b3bc-44e59230145d")]
            public virtual Ranorex.Cell CellN3
            {
                get
                {
                    return _celln3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellN3 item info.
            /// </summary>
            [RepositoryItemInfo("5c1963a0-66c5-4f3c-b3bc-44e59230145d")]
            public virtual RepoItemInfo CellN3Info
            {
                get
                {
                    return _celln3Info;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("b07666dd-bc40-4860-a007-3b85a4846b0a")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("b07666dd-bc40-4860-a007-3b85a4846b0a")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The SheetTab item.
            /// </summary>
            [RepositoryItem("c276ab32-ba10-4401-815b-73a9ca1713ce")]
            public virtual Ranorex.Button SheetTab
            {
                get
                {
                    return _sheettabInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SheetTab item info.
            /// </summary>
            [RepositoryItemInfo("c276ab32-ba10-4401-815b-73a9ca1713ce")]
            public virtual RepoItemInfo SheetTabInfo
            {
                get
                {
                    return _sheettabInfo;
                }
            }

            /// <summary>
            /// The BlankWorkbook item.
            /// </summary>
            [RepositoryItem("c37f6422-0e45-4d67-bcf2-d3627ea3cd76")]
            public virtual Ranorex.ListItem BlankWorkbook
            {
                get
                {
                    return _blankworkbookInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The BlankWorkbook item info.
            /// </summary>
            [RepositoryItemInfo("c37f6422-0e45-4d67-bcf2-d3627ea3cd76")]
            public virtual RepoItemInfo BlankWorkbookInfo
            {
                get
                {
                    return _blankworkbookInfo;
                }
            }

            /// <summary>
            /// The Sheet1 folder.
            /// </summary>
            [RepositoryFolder("a46060b2-e480-4274-a424-ff83014ca950")]
            public virtual ExcelTest1RepositoryFolders.Sheet1Folder Sheet1
            {
                get { return _sheet1; }
            }

            /// <summary>
            /// The CloseWindow folder.
            /// </summary>
            [RepositoryFolder("a6cf2df8-e8cd-4ed9-8bb4-8077ffd52730")]
            public virtual ExcelTest1RepositoryFolders.CloseWindowFolder CloseWindow
            {
                get { return _closewindow; }
            }

            /// <summary>
            /// The FontTests folder.
            /// </summary>
            [RepositoryFolder("2e1b4b74-7491-4d6d-94d2-cfed9778a6b9")]
            public virtual ExcelTest1RepositoryFolders.FontTestsFolder FontTests
            {
                get { return _fonttests; }
            }
        }

        /// <summary>
        /// The Sheet1Folder folder.
        /// </summary>
        [RepositoryFolder("a46060b2-e480-4274-a424-ff83014ca950")]
        public partial class Sheet1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _celli19Info;
            RepoItemInfo _cellb2Info;
            RepoItemInfo _cellk21Info;
            RepoItemInfo _cellm29Info;
            RepoItemInfo _cellb4Info;
            RepoItemInfo _celli20Info;
            RepoItemInfo _celll24Info;
            RepoItemInfo _cellj20Info;
            RepoItemInfo _cellg7Info;
            RepoItemInfo _cellg8Info;
            RepoItemInfo _celld1Info;
            RepoItemInfo _celld2Info;
            RepoItemInfo _celle1Info;
            RepoItemInfo _celle2Info;
            RepoItemInfo _cellj13Info;

            /// <summary>
            /// Creates a new Sheet1  folder.
            /// </summary>
            public Sheet1Folder(RepoGenBaseFolder parentFolder) :
                    base("Sheet1", ".//table[@name='Sheet1']", parentFolder, 30000, null, false, "a46060b2-e480-4274-a424-ff83014ca950", "")
            {
                _celli19Info = new RepoItemInfo(this, "CellI19", "row[@index='19']/cell[@address='I19']", "", 30000, null, "063bab1b-9de9-4f48-9633-fd09e33199b6");
                _cellb2Info = new RepoItemInfo(this, "CellB2", "row[@index='2']/cell[@address='B2']", "", 30000, null, "fed853a1-db13-4816-8768-cb27f843dbe0");
                _cellk21Info = new RepoItemInfo(this, "CellK21", "row[@index='21']/cell[@address='K21']", "", 30000, null, "b1cbdd07-c552-4109-8af9-36b64f15d0fd");
                _cellm29Info = new RepoItemInfo(this, "CellM29", "row[@index='29']/cell[@address='M29']", "", 30000, null, "3ff4b345-779a-47b7-9df9-05dbc2b1dcd4");
                _cellb4Info = new RepoItemInfo(this, "CellB4", "row[@index='4']/cell[@address='B4']", "", 30000, null, "3d2352d0-f4bb-4dde-bd00-73718ef15778");
                _celli20Info = new RepoItemInfo(this, "CellI20", "row[@index='20']/cell[@address='I20']", "", 30000, null, "bfddcf94-a755-4458-8df5-2493f41f113d");
                _celll24Info = new RepoItemInfo(this, "CellL24", "row[@index='24']/cell[@address='L24']", "", 30000, null, "c2260741-9c1c-4ef2-bcd2-6bd8c61a233f");
                _cellj20Info = new RepoItemInfo(this, "CellJ20", "row[@index='20']/cell[@address='J20']", "", 30000, null, "5935004e-b75b-4359-bcce-4ad489472080");
                _cellg7Info = new RepoItemInfo(this, "CellG7", "row[@index='7']/cell[@address='G7']", "", 30000, null, "fbc59eb5-965b-412e-a613-51452a67a165");
                _cellg8Info = new RepoItemInfo(this, "CellG8", "row[@index='8']/cell[@address='G8']", "", 30000, null, "3c0e3093-d290-4390-bb45-0cf18c7b9c3b");
                _celld1Info = new RepoItemInfo(this, "CellD1", "row[@index='1']/cell[@address='D1']", "", 30000, null, "21e91358-ca0b-485a-a7a8-4af36970bc7e");
                _celld2Info = new RepoItemInfo(this, "CellD2", "row[@index='2']/cell[@address='D2']", "", 30000, null, "ec41adf5-407f-435e-92a8-d59015d6b0b2");
                _celle1Info = new RepoItemInfo(this, "CellE1", "row[@index='1']/cell[@address='E1']", "", 30000, null, "fecf690d-836c-4d57-9ad8-b4e27a979662");
                _celle2Info = new RepoItemInfo(this, "CellE2", "row[@index='2']/cell[@address='E2']", "", 30000, null, "1ca911cb-e69d-4919-9ef0-b89f302de691");
                _cellj13Info = new RepoItemInfo(this, "CellJ13", "row[@index='13']/cell[@address='J13']", "", 30000, null, "9d592cc7-9d45-4460-9512-125d732760a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a46060b2-e480-4274-a424-ff83014ca950")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a46060b2-e480-4274-a424-ff83014ca950")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CellI19 item.
            /// </summary>
            [RepositoryItem("063bab1b-9de9-4f48-9633-fd09e33199b6")]
            public virtual Ranorex.Cell CellI19
            {
                get
                {
                    return _celli19Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellI19 item info.
            /// </summary>
            [RepositoryItemInfo("063bab1b-9de9-4f48-9633-fd09e33199b6")]
            public virtual RepoItemInfo CellI19Info
            {
                get
                {
                    return _celli19Info;
                }
            }

            /// <summary>
            /// The CellB2 item.
            /// </summary>
            [RepositoryItem("fed853a1-db13-4816-8768-cb27f843dbe0")]
            public virtual Ranorex.Cell CellB2
            {
                get
                {
                    return _cellb2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellB2 item info.
            /// </summary>
            [RepositoryItemInfo("fed853a1-db13-4816-8768-cb27f843dbe0")]
            public virtual RepoItemInfo CellB2Info
            {
                get
                {
                    return _cellb2Info;
                }
            }

            /// <summary>
            /// The CellK21 item.
            /// </summary>
            [RepositoryItem("b1cbdd07-c552-4109-8af9-36b64f15d0fd")]
            public virtual Ranorex.Cell CellK21
            {
                get
                {
                    return _cellk21Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellK21 item info.
            /// </summary>
            [RepositoryItemInfo("b1cbdd07-c552-4109-8af9-36b64f15d0fd")]
            public virtual RepoItemInfo CellK21Info
            {
                get
                {
                    return _cellk21Info;
                }
            }

            /// <summary>
            /// The CellM29 item.
            /// </summary>
            [RepositoryItem("3ff4b345-779a-47b7-9df9-05dbc2b1dcd4")]
            public virtual Ranorex.Cell CellM29
            {
                get
                {
                    return _cellm29Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellM29 item info.
            /// </summary>
            [RepositoryItemInfo("3ff4b345-779a-47b7-9df9-05dbc2b1dcd4")]
            public virtual RepoItemInfo CellM29Info
            {
                get
                {
                    return _cellm29Info;
                }
            }

            /// <summary>
            /// The CellB4 item.
            /// </summary>
            [RepositoryItem("3d2352d0-f4bb-4dde-bd00-73718ef15778")]
            public virtual Ranorex.Cell CellB4
            {
                get
                {
                    return _cellb4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellB4 item info.
            /// </summary>
            [RepositoryItemInfo("3d2352d0-f4bb-4dde-bd00-73718ef15778")]
            public virtual RepoItemInfo CellB4Info
            {
                get
                {
                    return _cellb4Info;
                }
            }

            /// <summary>
            /// The CellI20 item.
            /// </summary>
            [RepositoryItem("bfddcf94-a755-4458-8df5-2493f41f113d")]
            public virtual Ranorex.Cell CellI20
            {
                get
                {
                    return _celli20Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellI20 item info.
            /// </summary>
            [RepositoryItemInfo("bfddcf94-a755-4458-8df5-2493f41f113d")]
            public virtual RepoItemInfo CellI20Info
            {
                get
                {
                    return _celli20Info;
                }
            }

            /// <summary>
            /// The CellL24 item.
            /// </summary>
            [RepositoryItem("c2260741-9c1c-4ef2-bcd2-6bd8c61a233f")]
            public virtual Ranorex.Cell CellL24
            {
                get
                {
                    return _celll24Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellL24 item info.
            /// </summary>
            [RepositoryItemInfo("c2260741-9c1c-4ef2-bcd2-6bd8c61a233f")]
            public virtual RepoItemInfo CellL24Info
            {
                get
                {
                    return _celll24Info;
                }
            }

            /// <summary>
            /// The CellJ20 item.
            /// </summary>
            [RepositoryItem("5935004e-b75b-4359-bcce-4ad489472080")]
            public virtual Ranorex.Cell CellJ20
            {
                get
                {
                    return _cellj20Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellJ20 item info.
            /// </summary>
            [RepositoryItemInfo("5935004e-b75b-4359-bcce-4ad489472080")]
            public virtual RepoItemInfo CellJ20Info
            {
                get
                {
                    return _cellj20Info;
                }
            }

            /// <summary>
            /// The CellG7 item.
            /// </summary>
            [RepositoryItem("fbc59eb5-965b-412e-a613-51452a67a165")]
            public virtual Ranorex.Cell CellG7
            {
                get
                {
                    return _cellg7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellG7 item info.
            /// </summary>
            [RepositoryItemInfo("fbc59eb5-965b-412e-a613-51452a67a165")]
            public virtual RepoItemInfo CellG7Info
            {
                get
                {
                    return _cellg7Info;
                }
            }

            /// <summary>
            /// The CellG8 item.
            /// </summary>
            [RepositoryItem("3c0e3093-d290-4390-bb45-0cf18c7b9c3b")]
            public virtual Ranorex.Cell CellG8
            {
                get
                {
                    return _cellg8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellG8 item info.
            /// </summary>
            [RepositoryItemInfo("3c0e3093-d290-4390-bb45-0cf18c7b9c3b")]
            public virtual RepoItemInfo CellG8Info
            {
                get
                {
                    return _cellg8Info;
                }
            }

            /// <summary>
            /// The CellD1 item.
            /// </summary>
            [RepositoryItem("21e91358-ca0b-485a-a7a8-4af36970bc7e")]
            public virtual Ranorex.Cell CellD1
            {
                get
                {
                    return _celld1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellD1 item info.
            /// </summary>
            [RepositoryItemInfo("21e91358-ca0b-485a-a7a8-4af36970bc7e")]
            public virtual RepoItemInfo CellD1Info
            {
                get
                {
                    return _celld1Info;
                }
            }

            /// <summary>
            /// The CellD2 item.
            /// </summary>
            [RepositoryItem("ec41adf5-407f-435e-92a8-d59015d6b0b2")]
            public virtual Ranorex.Cell CellD2
            {
                get
                {
                    return _celld2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellD2 item info.
            /// </summary>
            [RepositoryItemInfo("ec41adf5-407f-435e-92a8-d59015d6b0b2")]
            public virtual RepoItemInfo CellD2Info
            {
                get
                {
                    return _celld2Info;
                }
            }

            /// <summary>
            /// The CellE1 item.
            /// </summary>
            [RepositoryItem("fecf690d-836c-4d57-9ad8-b4e27a979662")]
            public virtual Ranorex.Cell CellE1
            {
                get
                {
                    return _celle1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellE1 item info.
            /// </summary>
            [RepositoryItemInfo("fecf690d-836c-4d57-9ad8-b4e27a979662")]
            public virtual RepoItemInfo CellE1Info
            {
                get
                {
                    return _celle1Info;
                }
            }

            /// <summary>
            /// The CellE2 item.
            /// </summary>
            [RepositoryItem("1ca911cb-e69d-4919-9ef0-b89f302de691")]
            public virtual Ranorex.Cell CellE2
            {
                get
                {
                    return _celle2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellE2 item info.
            /// </summary>
            [RepositoryItemInfo("1ca911cb-e69d-4919-9ef0-b89f302de691")]
            public virtual RepoItemInfo CellE2Info
            {
                get
                {
                    return _celle2Info;
                }
            }

            /// <summary>
            /// The CellJ13 item.
            /// </summary>
            [RepositoryItem("9d592cc7-9d45-4460-9512-125d732760a8")]
            public virtual Ranorex.Cell CellJ13
            {
                get
                {
                    return _cellj13Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellJ13 item info.
            /// </summary>
            [RepositoryItemInfo("9d592cc7-9d45-4460-9512-125d732760a8")]
            public virtual RepoItemInfo CellJ13Info
            {
                get
                {
                    return _cellj13Info;
                }
            }
        }

        /// <summary>
        /// The CloseWindowFolder folder.
        /// </summary>
        [RepositoryFolder("a6cf2df8-e8cd-4ed9-8bb4-8077ffd52730")]
        public partial class CloseWindowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dontsaveInfo;
            RepoItemInfo _close1Info;
            RepoItemInfo _closeInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new CloseWindow  folder.
            /// </summary>
            public CloseWindowFolder(RepoGenBaseFolder parentFolder) :
                    base("CloseWindow", "", parentFolder, 30000, null, false, "a6cf2df8-e8cd-4ed9-8bb4-8077ffd52730", "")
            {
                _dontsaveInfo = new RepoItemInfo(this, "DontSave", "?/form[@name>'Save your changes to this']/?/?/button[@name='Don''t Save']", ".//button[@name='Don''t Save']", 30000, null, "d6c2650d-bd6b-415d-86c9-726a135f051a");
                _close1Info = new RepoItemInfo(this, "Close1", "?/?/button[@automationid='Close']", "?/?/button[@automationid='Close']", 30000, null, "7dce9d9c-1304-4228-bf05-ca5cf9cf8a93");
                _closeInfo = new RepoItemInfo(this, "Close", "element[@class='EXCEL2']/container[@caption='Ribbon']//container[@name='Ribbon']/button[@name='Close']", ".//button[@name='Close']", 30000, null, "d9873d28-ffd6-425a-a18a-1bcf8d6446e0");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "?/form[@name>'Save your changes to this']/?/?/button[@name='Cancel']", "", 30000, null, "0f899274-839c-4202-ac1f-546aa18a51b5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a6cf2df8-e8cd-4ed9-8bb4-8077ffd52730")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6cf2df8-e8cd-4ed9-8bb4-8077ffd52730")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DontSave item.
            /// </summary>
            [RepositoryItem("d6c2650d-bd6b-415d-86c9-726a135f051a")]
            public virtual Ranorex.Button DontSave
            {
                get
                {
                    return _dontsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DontSave item info.
            /// </summary>
            [RepositoryItemInfo("d6c2650d-bd6b-415d-86c9-726a135f051a")]
            public virtual RepoItemInfo DontSaveInfo
            {
                get
                {
                    return _dontsaveInfo;
                }
            }

            /// <summary>
            /// The Close1 item.
            /// </summary>
            [RepositoryItem("7dce9d9c-1304-4228-bf05-ca5cf9cf8a93")]
            public virtual Ranorex.Button Close1
            {
                get
                {
                    return _close1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close1 item info.
            /// </summary>
            [RepositoryItemInfo("7dce9d9c-1304-4228-bf05-ca5cf9cf8a93")]
            public virtual RepoItemInfo Close1Info
            {
                get
                {
                    return _close1Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("d9873d28-ffd6-425a-a18a-1bcf8d6446e0")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("d9873d28-ffd6-425a-a18a-1bcf8d6446e0")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("0f899274-839c-4202-ac1f-546aa18a51b5")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("0f899274-839c-4202-ac1f-546aa18a51b5")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The FontTestsFolder folder.
        /// </summary>
        [RepositoryFolder("2e1b4b74-7491-4d6d-94d2-cfed9778a6b9")]
        public partial class FontTestsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;

            /// <summary>
            /// Creates a new FontTests  folder.
            /// </summary>
            public FontTestsFolder(RepoGenBaseFolder parentFolder) :
                    base("FontTests", "", parentFolder, 0, null, false, "2e1b4b74-7491-4d6d-94d2-cfed9778a6b9", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", ".//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Home']/container[@name='Font']/combobox[@name='Font']/button[@name='Open']", ".//button[@name='Open']", 30000, null, "7b408168-4c7a-440f-b31a-39d8293d60c4");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e1b4b74-7491-4d6d-94d2-cfed9778a6b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("7b408168-4c7a-440f-b31a-39d8293d60c4")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("7b408168-4c7a-440f-b31a-39d8293d60c4")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }
        }

        /// <summary>
        /// The ProgramsAppFolder folder.
        /// </summary>
        [RepositoryFolder("6fc172e3-5f96-4653-8c6b-c8b9cceccd0e")]
        public partial class ProgramsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemsviewInfo;
            RepoItemInfo _systemitemnamedisplayInfo;

            /// <summary>
            /// Creates a new Programs  folder.
            /// </summary>
            public ProgramsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Programs", "/form[@title='Programs']", parentFolder, 30000, null, true, "6fc172e3-5f96-4653-8c6b-c8b9cceccd0e", "")
            {
                _itemsviewInfo = new RepoItemInfo(this, "ItemsView", "element[@class='ShellTabWindowClass']//element[@instance='1']/container[@caption='ShellView']/?/?/list[@accessiblename='Items View']", ".//list[@accessiblename='Items View']", 30000, null, "9f7d7262-7f40-4312-9487-69d4ad367423");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='ShellTabWindowClass']//element[@instance='1']//listitem[@automationid='9']/text[@automationid='System.ItemNameDisplay']", ".//listitem[@automationid='9']/text[@automationid='System.ItemNameDisplay']", 30000, null, "824ff0a5-dde7-4190-b043-a41674ef7398");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6fc172e3-5f96-4653-8c6b-c8b9cceccd0e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6fc172e3-5f96-4653-8c6b-c8b9cceccd0e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemsView item.
            /// </summary>
            [RepositoryItem("9f7d7262-7f40-4312-9487-69d4ad367423")]
            public virtual Ranorex.List ItemsView
            {
                get
                {
                    return _itemsviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ItemsView item info.
            /// </summary>
            [RepositoryItemInfo("9f7d7262-7f40-4312-9487-69d4ad367423")]
            public virtual RepoItemInfo ItemsViewInfo
            {
                get
                {
                    return _itemsviewInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("824ff0a5-dde7-4190-b043-a41674ef7398")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("824ff0a5-dde7-4190-b043-a41674ef7398")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
