///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExcelTest1
{
    public partial class NewSheetTest
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void NewSheet()
        {
        	
        	var newSheet = repo.Book16Excel.Self.FindSingle<Ranorex.Button>("//button[@name='Add Sheet']");
        	newSheet.DoubleClick();
        	newSheet.PressKeys(HanNavel.ToString());
        	newSheet.PressKeys("{Enter}");
        }

        public void CellFill()
        {
        	var cell = repo.Book16Excel.Self.FindSingle<Ranorex.Cell>("//table[@name='" + HanNavel.ToString() + "']//cell[@address='A1']");
        	cell.DoubleClick();
        	cell.PressKeys(HanNavel);
        	cell.PressKeys("{Enter}");
        }

    }
}
