///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExcelTest1
{
    public partial class TextInsertion
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CellParameterChange()
        {
        	repo.Book16Excel.CellA1.DoubleClick();
        	
        	repo.Book16Excel.CellA1.PressKeys(HanNavel);
        	
        }

        public string CellParameterGet()
        {
        	var text = repo.Book16Excel.CellH8.Text.ToString();
        	if(text==""||text==null)
        	{
        		CellValue = ElseVariable;
        		return "AB/CD rulz";
        	}
        	else
        	{
        		CellValue = text;
        		return "Han Navel is our president";
        	}
        }

        public void CellParametersSet()
        {
        	repo.Book16Excel.CellD5.DoubleClick();
        	repo.Book16Excel.CellD5.PressKeys(CellParameterGet());
        	repo.Book16Excel.CellD5.PressKeys("{Enter}");
        	repo.Book16Excel.CellB3.DoubleClick();
        	repo.Book16Excel.CellB3.PressKeys(CellValue);
        	repo.Book16Excel.CellB3.PressKeys("{Enter}");
        	repo.Book16Excel.CellD5.Click();
        	repo.Book16Excel.CellD5.PressKeys("{Delete}");
        	var title = repo.Book16Excel.TitleBarBook26Excel.Text;
        	repo.Book16Excel.CellE7.DoubleClick();
        	repo.Book16Excel.CellE7.PressKeys(title);
        	repo.Book16Excel.CellE7.PressKeys("{Enter}");
        }

        public void ValidateCellContent()
        {
        	var Cell = repo.Book16Excel.TitleBarBook26Excel.Element.GetAttributeValueText("name").Replace("?","");
			var title = repo.Book16Excel.TitleBarBook26Excel.Text;
        	Validate.AreEqual(Cell,title,"Comparing the cell content...");
        }
    }
}
